///////////////////////////////////////////////////////////////////////////////
// RTC_StateMachine.h
#pragma once

#include "RTC_StateMachineInterfaces.h"
//#include "RTC_Def.h"
#include "ResourceMngr.h"
#include "Fsm.h"
#include "FsmKv.h"
#include "PlanMngr.h"
#include "Bgm.h"
#include "Bsm.h"
#include "Igs.h"

class CRTC_StateMachine 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_RTC_StateMachineCRTC_StateMachine)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CRTC_StateMachine();
	virtual	~CRTC_StateMachine();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>
	/*== Custom Define ====================================================*/
	CResourceMngr ResourceMngr; //resource manager
	CFsm		  Fsm{ &ResourceMngr }; //state machine manager
	CFsmKv		  FsmKv{ &ResourceMngr }; //kv state machine manager
	CFsm*         FsmPtr = &Fsm;
	CPlanMngr     PlanMngr{ &ResourceMngr };
	CBgm		  Bgm{ &ResourceMngr };
	CBsm		  Bsm{ &ResourceMngr };
	CIgs          Igs{ &ResourceMngr };
	/*== Define End =======================================================*/

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	RTC_StateMachineInputsFsm m_InputsFsm;
	RTC_StateMachineOutputsFsm m_OutputsFsm;
	RTC_StateMachineInputsSubFsm m_InputsSubFsm;
	RTC_StateMachineOutputsSubFsm m_OutputsSubFsm;
	RTC_StateMachineInputsOGR m_InputsOGR;
	RTC_StateMachineOutputsOGR m_OutputsOGR;
	RTC_StateMachineInputsBeam m_InputsBeam;
	RTC_StateMachineOutputsBeam m_OutputsBeam;
	RTC_StateMachineInputsDose m_InputsDose;
	RTC_StateMachineOutputsDose m_OutputsDose;
	RTC_StateMachinePlanInputs m_PlanInputs;
	RTC_StateMachinePlanOutputs m_PlanOutputs;
	RTC_StateMachineInputsBgmPlan m_InputsBgmPlan;
	RTC_StateMachineOutputsBgmPlan m_OutputsBgmPlan;
	RTC_StateMachineInputsIgsSlv m_InputsIgsSlv;
	RTC_StateMachineOutputsIgsSlv m_OutputsIgsSlv;
	RTC_StateMachineInputsBsm m_InputsBsm;
	RTC_StateMachineOutputsBsm m_OutputsBsm;
	RTC_StateMachineInputsVMAT m_InputsVMAT;
	RTC_StateMachineOutputsVMAT m_OutputsVMAT;
	RTC_StateMachineInputsCtrlState m_InputsCtrlState;
	RTC_StateMachineOutputsCtrlState m_OutputsCtrlState;
	RTC_StateMachineInputsOnGantryHD m_InputsOnGantryHD;
	RTC_StateMachineOutputsOnGantryHD m_OutputsOnGantryHD;
	RTC_StateMachineInputsBsmFmGUI m_InputsBsmFmGUI;
	RTC_StateMachineOutptsBsmToGUI m_OutptsBsmToGUI;
	RTC_StateMachineInputsIgs m_InputsIgs;
	RTC_StateMachineOutputsIgs m_OutputsIgs;
	RTC_StateMachineFmDevices m_FmDevices;
	RTC_StateMachineIUTMonitor m_IUTMonitor;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	/*== Custom Define ====================================================*/
	BOOL InitResource(VOID);
	BOOL GetCurrentSysTime(ITcTask* ipTask);
	VOID SwitchCurrentFsm(VOID);
	/*== Define End =======================================================*/
};
