///////////////////////////////////////////////////////////////////////////////
// RTC_StateMachineInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "RTC_StateMachineServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
