///////////////////////////////////////////////////////////////////////////////
// RTC_StateMachineClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RTC_StateMachineClassFactory.h"
#include "RTC_StateMachineServices.h"
#include "RTC_StateMachineVersion.h"
#include "RTC_StateMachine.h"

BEGIN_CLASS_MAP(CRTC_StateMachineClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_RTC_StateMachineCRTC_StateMachine, SRVNAME_RTC_STATEMACHINE "!CRTC_StateMachine", CRTC_StateMachine)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRTC_StateMachineClassFactory::CRTC_StateMachineClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_RTC_STATEMACHINE)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(RTC_StateMachine));
#endif //defined(TCDBG_UNIT_VERSION)
}

