///////////////////////////////////////////////////////////////////////////////
// TCPServerClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TCPServerClassFactory.h"
#include "TCPServerServices.h"
#include "TCPServerVersion.h"
#include "TCPServer.h"

BEGIN_CLASS_MAP(CTCPServerClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_TCPServerCTCPServer, SRVNAME_TCPSERVER "!CTCPServer", CTCPServer)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTCPServerClassFactory::CTCPServerClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TCPSERVER)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(TCPServer));
#endif //defined(TCDBG_UNIT_VERSION)
}

